### ISSUE TITLE
多账号的支持

### ISSUE THREAD

**Issue by nodyang** [niltor/open-pdd-net-sdk#10]
1  PddCommonApi.ClientId = "ID";
    PddCommonApi.ClientSecret = "Secret";  我想一个平台 多个店铺。可以支持下不。我们下属的公司都是单独的店铺 不想部署好几套

**Comment by niltor** [comment]
@nodyang  你好，你提出的需求很有实际的应用价值。
当前sdk集成到ASP.NET Core应用，默认是通过依赖注入，从配置中获取店铺相关配置信息，后续使用该服务的请求都只针对这一个店铺账号。

当前考虑，提供新的构造方法，在创建服务实例的时候，可传入配置信息，使用该实例的请求，则以传入的配置信息为准，以实现动态配置的目的。

虽然 实现该功能并不复杂，但我仍然无法提供一个确切的时间，预计在12月底之前可以发布。

**Comment by niltor** [comment]
@nodyang  我最近发布了一个测试版，针对多账号的，因为我没有认证通过的拼多多的账号，没有办法进行测试，不知道你是否可以试用，并提供反馈！
你可以直接拉取最新代码，或通过nuget使用[V2.2.0-beta](https://www.nuget.org/packages/MSDev.PddOpenSdk.AspNetCore/2.2.0-beta)。

**Comment by nodyang** [comment]
好的。我们目前部署到拼多多塔内。解决脱敏数据的问题。可能升级版没那么快 我会及时反馈
