### ISSUE TITLE
更新7.0后订单列表查询和订单详情无效

### ISSUE THREAD

**Issue by Sunhelter** [niltor/open-pdd-net-sdk#18]
OrderApi.GetOrderInformationAsync
对应pdd.order.information.get订单详情接口

OrderApi.GetOrderListAsync
对应pdd.order.list.get订单列表查询接口

更新7.0版后这两个订单查询函数丢失了

**Comment by niltor** [comment]
已确认，将在最近修复

**Comment by niltor** [comment]
@Sunhelter 已在7.0.1版本进行修复
